from abc import ABC, abstractmethod
import os
from typing import Optional

from movie_search.config import DEFAULT_GEMINI_MODEL


class BaseLLMProvider(ABC):
    @abstractmethod
    def generate(self, prompt: str, system_instruction: Optional[str] = None) -> str:
        """Generate text from the LLM given a prompt and optional system instruction."""
        pass


class GeminiProvider(BaseLLMProvider):
    """LLM provider implementation for Google Gemini using google-genai SDK."""

    def __init__(
        self,
        api_key: Optional[str] = None,
        model_name: str = DEFAULT_GEMINI_MODEL,
    ):
        self.api_key = api_key or os.environ.get("GEMINI_API_KEY")
        if not self.api_key:
            raise ValueError(
                "Gemini API key is required. "
                "Please provide it via --api-key <KEY>, set the GEMINI_API_KEY "
                "environment variable, or put GEMINI_API_KEY=your_key in a .env file."
            )

        self.model_name = model_name
        try:
            from google import genai
            from google.genai import types

            self._client = genai.Client(api_key=self.api_key)
            self._types = types
        except ImportError as exc:
            raise ImportError(
                "google-genai is not installed. Please run `uv sync` or `pip install google-genai`."
            ) from exc

    def generate(self, prompt: str, system_instruction: Optional[str] = None) -> str:
        config_args = {}
        if system_instruction:
            config_args["system_instruction"] = system_instruction

        config = self._types.GenerateContentConfig(**config_args) if config_args else None

        response = self._client.models.generate_content(
            model=self.model_name,
            contents=prompt,
            config=config,
        )

        if not response or not response.text:
            return "No response generated by the model."
        return response.text


class MockLLMProvider(BaseLLMProvider):
    """Mock LLM provider useful for offline testing and verification."""

    def __init__(self, model_name: str = "mock-gemini"):
        self.model_name = model_name

    def generate(self, prompt: str, system_instruction: Optional[str] = None) -> str:
        return (
            "[Mock LLM Response]\n"
            "This is a simulated answer generated from retrieved movie context.\n"
            f"Prompt length: {len(prompt)} characters."
        )


def get_llm_provider(
    provider_name: str = "gemini",
    api_key: Optional[str] = None,
    model_name: Optional[str] = None,
) -> BaseLLMProvider:
    """Factory function to get an LLM provider."""
    name = provider_name.lower()
    if name in ("gemini", "google"):
        return GeminiProvider(
            api_key=api_key,
            model_name=model_name or DEFAULT_GEMINI_MODEL,
        )
    elif name in ("mock", "test"):
        return MockLLMProvider(model_name=model_name or "mock-model")
    else:
        raise ValueError(f"Unsupported LLM provider: {provider_name}. Choose 'gemini' or 'mock'.")
